name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ["ubuntu-20.04", "windows-latest"]

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: 8
    - name: Mount caches
      uses: actions/cache@v2
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.cache/coursier
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
    - name: Compile and test
      run: |
       sbt test
      shell: bash
    - name: Format check
      if: ${{ runner.os == 'Linux' }}
      run: |
        sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
  # Single final job for mergify.
  ci-passed:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: ':'
